// packages/svelte/src/GlassPanel.svelte
<script lang="ts">
  import { getContext, onDestroy, type Snippet } from "svelte";
  import { createShaderSurface, KUSSETSU_GLASS, type ShaderSurface, type Uniforms } from "@kussetsu/core";
  import { GLASS_SCENE_KEY, type GlassSceneContext } from "./context";

  interface Props {
    children: Snippet;
    class?: string;
    /** Corner radius in CSS px. Defaults to the element's computed border-radius. */
    radius?: number;
    /** Frost amount (0 = perfectly clear, see-through glass). */
    blur?: number;
    /** Backdrop blur — a clean depth-of-field blur of the wallpaper (no frosting). */
    bgBlur?: number;
    /** Edge bend strength. */
    refraction?: number;
    /** Chromatic split at the rim. */
    dispersion?: number;
    /** Rim refraction band width. */
    rim?: number;
    /** Glass color (any CSS color). Drives both the tint wash and the solid frost. */
    color?: string;
    /** Tint amount toward `color` (0 = none). */
    tint?: number;
    /** Highlight intensity. */
    specular?: number;
    /** Make the panel draggable. */
    drag?: boolean;
    [key: string]: unknown;
  }

  let {
    children,
    class: className = "",
    radius,
    blur = 0,
    bgBlur = 0,
    refraction = 0.05,
    dispersion = 0.006,
    rim = 0.05,
    color = "#e6ebf2",
    tint = 0.04,
    specular = 1,
    drag = false,
    ...rest
  }: Props = $props();

  const scene = getContext<GlassSceneContext>(GLASS_SCENE_KEY);

  // Parse any CSS color string to linear-ish 0..1 RGB (re-runs only on change).
  const DEFAULT_RGB: [number, number, number] = [0.902, 0.922, 0.949];
  function parseColor(c: string): [number, number, number] {
    try {
      const ctx = document.createElement("canvas").getContext("2d");
      if (!ctx) return DEFAULT_RGB;
      ctx.fillStyle = c;
      const s = ctx.fillStyle;
      if (s[0] === "#") {
        const n = parseInt(s.slice(1, 7), 16);
        return [((n >> 16) & 255) / 255, ((n >> 8) & 255) / 255, (n & 255) / 255];
      }
      const nums = s.match(/[\d.]+/g);
      if (nums && nums.length >= 3) return [+nums[0] / 255, +nums[1] / 255, +nums[2] / 255];
      return DEFAULT_RGB;
    } catch {
      return DEFAULT_RGB;
    }
  }
  let colorRgb = $derived(parseColor(color));

  let panelEl: HTMLDivElement;
  let surface: ShaderSurface | null = null;
  let resolvedRadius = 24;

  // Drag offset (transform). origin/size are recomputed from rects each frame,
  // so dragging keeps the glass glued to the right backdrop pixels for free.
  let x = $state(0);
  let y = $state(0);
  let hover = $state(0);
  let dragging = false;
  let sx = 0;
  let sy = 0;
  let bx = 0;
  let by = 0;

  // Pushed to the shader every frame. Reads the current (reactive) prop values,
  // so binding props to sliders updates the glass live — with zero uniform code
  // on the consumer's side.
  function frameUniforms(): Uniforms | null {
    const sceneEl = scene?.getSceneEl();
    if (!sceneEl || !panelEl) return null;
    const s = sceneEl.getBoundingClientRect();
    const p = panelEl.getBoundingClientRect();
    const w = s.width || 1;
    const h = s.height || 1;
    return {
      origin: [(p.left - s.left) / w, (p.top - s.top) / h],
      size: [p.width / w, p.height / h],
      radius: radius ?? resolvedRadius,
      blur: blur * 0.001,
      bgBlur: bgBlur * 0.001,
      refraction,
      dispersion,
      rim,
      color: colorRgb,
      tintAmount: tint,
      specular,
      hover,
    };
  }

  function cssGlassFallback() {
    if (!panelEl) return;
    panelEl.style.backdropFilter = "blur(8px) saturate(150%)";
    (panelEl.style as CSSStyleDeclaration & { webkitBackdropFilter?: string }).webkitBackdropFilter =
      "blur(8px) saturate(150%)";
    panelEl.style.background = "rgba(255,255,255,0.10)";
  }

  $effect(() => {
    const backdrop = scene?.backdrop; // reactive dependency
    if (surface || !panelEl) return;
    if (scene?.failed) {
      cssGlassFallback();
      return;
    }
    if (!backdrop) return;

    resolvedRadius = radius ?? (parseFloat(getComputedStyle(panelEl).borderTopLeftRadius) || 24);
    surface = createShaderSurface(panelEl, {
      wgsl: KUSSETSU_GLASS,
      textures: { backdrop },
      uniforms: {
        origin: [0, 0],
        size: [1, 1],
        radius: resolvedRadius,
        blur: blur * 0.001,
        bgBlur: bgBlur * 0.001,
        refraction,
        dispersion,
        rim,
        tint: [1, 1, 1],
        tintAmount: tint,
        specular,
        hover: 0,
      },
      uniformsPerFrame: frameUniforms,
      fallback: { kind: "css", value: "rgba(255,255,255,0.10)" },
    });
  });

  onDestroy(() => surface?.destroy());

  function onpointerdown(e: PointerEvent) {
    if (!drag) return;
    dragging = true;
    hover = 1;
    sx = e.clientX;
    sy = e.clientY;
    bx = x;
    by = y;
    (e.currentTarget as HTMLElement).setPointerCapture(e.pointerId);
  }
  function onpointermove(e: PointerEvent) {
    if (!dragging) return;
    x = bx + (e.clientX - sx);
    y = by + (e.clientY - sy);
  }
  function onpointerup() {
    dragging = false;
  }
</script>

<div
  bind:this={panelEl}
  class={className}
  data-kussetsu-panel
  style="position: relative; isolation: isolate; transform: translate({x}px, {y}px); {radius != null ? `border-radius: ${radius}px;` : ''} {drag ? 'cursor: grab; touch-action: none;' : ''}"
  {onpointerdown}
  {onpointermove}
  {onpointerup}
  onpointerenter={() => (hover = 1)}
  onpointerleave={() => !dragging && (hover = 0)}
  {...rest}
>
  {@render children()}
</div>

// packages/react/src/GlassPanel.tsx
import { useContext, useEffect, useMemo, useRef, useState } from "react";
import type { CSSProperties, HTMLAttributes, PointerEvent as ReactPointerEvent, ReactNode } from "react";
import { createShaderSurface, KUSSETSU_GLASS, type ShaderSurface, type Uniforms } from "@kussetsu/core";
import { GlassSceneContext } from "./context";

const DEFAULT_RGB: [number, number, number] = [0.902, 0.922, 0.949];

/** Parse any CSS color string to 0..1 RGB via the canvas fillStyle trick. */
function parseColor(c: string): [number, number, number] {
  try {
    const ctx = document.createElement("canvas").getContext("2d");
    if (!ctx) return DEFAULT_RGB;
    ctx.fillStyle = c;
    const s = ctx.fillStyle;
    if (s[0] === "#") {
      const n = parseInt(s.slice(1, 7), 16);
      return [((n >> 16) & 255) / 255, ((n >> 8) & 255) / 255, (n & 255) / 255];
    }
    const nums = s.match(/[\d.]+/g);
    if (nums && nums.length >= 3) return [Number(nums[0]) / 255, Number(nums[1]) / 255, Number(nums[2]) / 255];
    return DEFAULT_RGB;
  } catch {
    return DEFAULT_RGB;
  }
}

function cssGlassFallback(el: HTMLElement) {
  el.style.backdropFilter = "blur(8px) saturate(150%)";
  (el.style as CSSStyleDeclaration & { webkitBackdropFilter?: string }).webkitBackdropFilter =
    "blur(8px) saturate(150%)";
  el.style.background = "rgba(255,255,255,0.10)";
}

export interface GlassPanelProps extends HTMLAttributes<HTMLDivElement> {
  children?: ReactNode;
  /** Corner radius in CSS px. Defaults to the element's computed border-radius. */
  radius?: number;
  /** Frost amount (0 = perfectly clear, see-through glass). */
  blur?: number;
  /** Backdrop blur — a clean depth-of-field blur of the wallpaper (no frosting). */
  bgBlur?: number;
  /** Edge bend strength. */
  refraction?: number;
  /** Chromatic split at the rim. */
  dispersion?: number;
  /** Rim refraction band width. */
  rim?: number;
  /** Glass color (any CSS color). Drives both the tint wash and the solid frost. */
  color?: string;
  /** Tint amount toward `color` (0 = none). */
  tint?: number;
  /** Highlight intensity. */
  specular?: number;
  /** Make the panel draggable. */
  drag?: boolean;
}

/**
 * A refractive glass panel. Drop it inside a <GlassScene>; it refracts the
 * scene's captured backdrop at its own rect while its children render as crisp,
 * accessible DOM on top.
 */
export function GlassPanel({
  children,
  radius,
  blur = 0,
  bgBlur = 0,
  refraction = 0.05,
  dispersion = 0.006,
  rim = 0.05,
  color = "#e6ebf2",
  tint = 0.04,
  specular = 1,
  drag = false,
  style,
  onPointerDown,
  onPointerMove,
  onPointerUp,
  onPointerEnter,
  onPointerLeave,
  ...rest
}: GlassPanelProps) {
  const scene = useContext(GlassSceneContext);
  const sceneRef = useRef(scene);
  sceneRef.current = scene;

  const panelRef = useRef<HTMLDivElement | null>(null);
  const surfaceRef = useRef<ShaderSurface | null>(null);
  const resolvedRadiusRef = useRef(24);
  const hoverRef = useRef(0);
  const dragRef = useRef({ dragging: false, sx: 0, sy: 0, bx: 0, by: 0 });
  const [pos, setPos] = useState({ x: 0, y: 0 });

  const colorRgb = useMemo(() => parseColor(color), [color]);

  // Latest uniform-driving values for the per-frame callback (no stale closures).
  const frameRef = useRef({ radius, blur, bgBlur, refraction, dispersion, rim, colorRgb, tint, specular });
  frameRef.current = { radius, blur, bgBlur, refraction, dispersion, rim, colorRgb, tint, specular };

  // Pushed to the shader every frame. Reads current rects + props, so binding
  // props to state updates the glass live with zero uniform code for the user.
  const frameUniforms = useRef((): Uniforms | null => {
    const sceneEl = sceneRef.current?.getSceneEl();
    const panelEl = panelRef.current;
    if (!sceneEl || !panelEl) return null;
    const s = sceneEl.getBoundingClientRect();
    const p = panelEl.getBoundingClientRect();
    const w = s.width || 1;
    const h = s.height || 1;
    const f = frameRef.current;
    return {
      origin: [(p.left - s.left) / w, (p.top - s.top) / h],
      size: [p.width / w, p.height / h],
      radius: f.radius ?? resolvedRadiusRef.current,
      blur: f.blur * 0.001,
      bgBlur: f.bgBlur * 0.001,
      refraction: f.refraction,
      dispersion: f.dispersion,
      rim: f.rim,
      color: f.colorRgb,
      tintAmount: f.tint,
      specular: f.specular,
      hover: hoverRef.current,
    };
  }).current;

  const backdrop = scene?.backdrop ?? null;
  const failed = scene?.failed ?? false;

  useEffect(() => {
    const panelEl = panelRef.current;
    if (!panelEl || surfaceRef.current) return;
    if (failed) {
      cssGlassFallback(panelEl);
      return;
    }
    if (!backdrop) return;

    resolvedRadiusRef.current =
      radius ?? (parseFloat(getComputedStyle(panelEl).borderTopLeftRadius) || 24);

    const surface = createShaderSurface(panelEl, {
      wgsl: KUSSETSU_GLASS,
      textures: { backdrop },
      uniforms: {
        origin: [0, 0],
        size: [1, 1],
        radius: resolvedRadiusRef.current,
        blur: blur * 0.001,
        bgBlur: bgBlur * 0.001,
        refraction,
        dispersion,
        rim,
        color: colorRgb,
        tintAmount: tint,
        specular,
        hover: 0,
      },
      uniformsPerFrame: frameUniforms,
      fallback: { kind: "css", value: "rgba(255,255,255,0.10)" },
    });
    surfaceRef.current = surface;
    return () => {
      surface.destroy();
      surfaceRef.current = null;
    };
    // Create once the backdrop is ready; live updates flow through frameUniforms.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [backdrop, failed]);

  const handlePointerDown = (e: ReactPointerEvent<HTMLDivElement>) => {
    onPointerDown?.(e);
    if (!drag) return;
    dragRef.current = { dragging: true, sx: e.clientX, sy: e.clientY, bx: pos.x, by: pos.y };
    hoverRef.current = 1;
    e.currentTarget.setPointerCapture(e.pointerId);
  };
  const handlePointerMove = (e: ReactPointerEvent<HTMLDivElement>) => {
    onPointerMove?.(e);
    const d = dragRef.current;
    if (!d.dragging) return;
    setPos({ x: d.bx + (e.clientX - d.sx), y: d.by + (e.clientY - d.sy) });
  };
  const handlePointerUp = (e: ReactPointerEvent<HTMLDivElement>) => {
    onPointerUp?.(e);
    dragRef.current.dragging = false;
  };
  const handlePointerEnter = (e: ReactPointerEvent<HTMLDivElement>) => {
    onPointerEnter?.(e);
    hoverRef.current = 1;
  };
  const handlePointerLeave = (e: ReactPointerEvent<HTMLDivElement>) => {
    onPointerLeave?.(e);
    if (!dragRef.current.dragging) hoverRef.current = 0;
  };

  const panelStyle: CSSProperties = {
    position: "relative",
    isolation: "isolate",
    transform: `translate(${pos.x}px, ${pos.y}px)`,
    ...(radius != null ? { borderRadius: `${radius}px` } : {}),
    ...(drag ? { cursor: "grab", touchAction: "none" } : {}),
    ...style,
  };

  return (
    <div
      ref={panelRef}
      data-kussetsu-panel=""
      style={panelStyle}
      onPointerDown={handlePointerDown}
      onPointerMove={handlePointerMove}
      onPointerUp={handlePointerUp}
      onPointerEnter={handlePointerEnter}
      onPointerLeave={handlePointerLeave}
      {...rest}
    >
      {children}
    </div>
  );
}
